# Generated by Django 3.2.12 on 2022-03-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_iplextrarunsconcededperseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todoentriesmodel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Ipldata',
        ),
        migrations.DeleteModel(
            name='Iplextrarunsconcededperseason',
        ),
        migrations.DeleteModel(
            name='Iplmatchesplayedvswon',
        ),
        migrations.DeleteModel(
            name='Iplmatcheswondata',
        ),
        migrations.DeleteModel(
            name='Ipltopeconomicalbowlers',
        ),
    ]
